#!/usr/bin/env python3
import psycopg2

DBName = "news"


mostPopularThreeArticles = """
                            SELECT articles.title as Title, count(log.path) AS ViewCounter
                            FROM articles, log
                            WHERE SUBSTRING(log.path, 10) = articles.slug
                            GROUP BY Title
                            ORDER BY (ViewCounter) DESC
                            LIMIT 3;
                           """
mostPopularArticleAuthors = """
                            SELECT authors.name as AuthorName, count(log.path) AS AuthorCounter
                            FROM authors , articles , log
                            WHERE authors.id = articles.author
                            AND SUBSTRING(log.path,10) = articles.slug
                            GROUP BY AuthorName
                            ORDER BY (AuthorCounter) DESC;
                           """

def DBConnection(query):
        """database connection and excution and result """
        db = psycopg2.connect(database=DBName)
        c = db.cursor()
        c.execute(query)
        result = c.fetchall()
        db.close()
        return result

def printMostPopularThreeArticles(result1):
    print("What are the most popular three articles of all time?")
    for Title, ViewCounter in result1:
        print("\"{}\" _ {} views".format(Title,ViewCounter))

def printMostPopularArticleAuthors(result2):
    print("Who are the most popular article authors of all time?")
    for Title, ViewCounter in result2:
        print("\"{}\" _ {} views".format(Title,ViewCounter))



def main():
        result1 = DBConnection (mostPopularThreeArticles)
        printMostPopularThreeArticles(result1)
        result2 = DBConnection (mostPopularArticleAuthors)
        printMostPopularArticleAuthors(result2)


if __name__ == '__main__':
    main()
